name: Build and test the esy package

on:
  - push

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - ubuntu-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Use Node.js 22.13.1
        uses: actions/setup-node@v6
        with:
          node-version: 22.13.1

      # Install `esy` to build the project
      # It also adds `shx` globally for cross-platform shell commands
      - name: Setup environment
        run:
          npm i -g esy@0.9.2
          npm i -g shx
        
      - name: Checkout code
        uses: actions/checkout@v6
      
      - name: Install and build
        run: |
          cd ./esy-test/
          esy install
          esy build
